cars = {'bmw':8.5,'bens':8.3,'audi':7.9}
ims = cars.items()
print(type(ims))
print(ims)
print(list(ims))
print(list(ims)[1])
kys = cars.keys()
print(type(kys))
print(list(kys))
vals = cars.values()
print(type(vals))
print(list(vals))
print(list(vals)[1])